"""initial migration

Revision ID: 022b98b43abe
Revises: 
Create Date: 2024-12-03 01:18:21.524098

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '022b98b43abe'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
